version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: assinaturas
    networks:
      - assinaturas
networks:
  assinaturas: